package br.edu.ifnmg.estudiofotografia.gui;

import br.edu.ifnmg.estudiofotografia.entity.Usuario;
import br.edu.ifnmg.estudiofotografia.repository.UsuarioDao;
import com.sun.jdi.connect.Connector;
import javax.swing.JOptionPane;

/**
 *
 * @author Rikelme
 */
public class CadastroUsuario extends javax.swing.JInternalFrame {

    private static CadastroUsuario instance;

    /**
     * Creates new form CadastroCliente
     */
    public CadastroUsuario() {
        initComponents();
    }

    public static CadastroUsuario getInstance() {
        if (instance == null) {
            instance = new CadastroUsuario();
        }
        return instance;
    }

    private void limparCampos() {
        tfCadastroUsuario.setText(null);
        ftfCadastroUsuarioSenha.setText(null);
        cboAdministrador.setSelected(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblUsuario = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        tfCadastroUsuario = new javax.swing.JTextField();
        ftfCadastroUsuarioSenha = new javax.swing.JFormattedTextField();
        btnCadastrar = new javax.swing.JButton();
        cboAdministrador = new javax.swing.JCheckBox();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro Usuario");

        lblUsuario.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblUsuario.setText("Usuario:");

        lblSenha.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblSenha.setText("Senha:");

        tfCadastroUsuario.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        ftfCadastroUsuarioSenha.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        btnCadastrar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        cboAdministrador.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cboAdministrador.setText("Administrador");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCadastrar)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSenha)
                            .addComponent(lblUsuario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfCadastroUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(ftfCadastroUsuarioSenha)
                            .addComponent(cboAdministrador))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(tfCadastroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenha)
                    .addComponent(ftfCadastroUsuarioSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(cboAdministrador)
                .addGap(18, 18, 18)
                .addComponent(btnCadastrar)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        Usuario usuario = new Usuario();
        UsuarioDao usuarioDao = new UsuarioDao();

        usuario.setNomeSistema(tfCadastroUsuario.getText());
        usuario.setSenha(ftfCadastroUsuarioSenha.getText());
        usuario.setAdministrador(cboAdministrador.isSelected());
        if (!tfCadastroUsuario.getText().isEmpty()) {
            if (!ftfCadastroUsuarioSenha.getText().isEmpty()) {
                Long id = usuarioDao.salvar(usuario);
                usuario.setId(id);
                limparCampos();
            } else JOptionPane.showMessageDialog(null, "Preencha o Campo: Senha");
        } else {
            JOptionPane.showMessageDialog(null, "Preencha todos os Campos");
        }


    }//GEN-LAST:event_btnCadastrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cboAdministrador;
    private javax.swing.JFormattedTextField ftfCadastroUsuarioSenha;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField tfCadastroUsuario;
    // End of variables declaration//GEN-END:variables
}
